2022-04-03 21:51:15,579 [dqn_agent3_wrapper] ERROR: 
Traceback (most recent call last):
  File "C:\Users\kinne\Desktop\bomberman\bomberman_rl\agents.py", line 248, in process_event
    event_result = getattr(module, event_name)(self.fake_self, *event_args)
  File "C:\Users\kinne\Desktop\bomberman\bomberman_rl\agent_code\dqn_agent3\train.py", line 38, in game_events_occurred
    self.Agent.UpdateWeights()
  File "C:\Users\kinne\Desktop\bomberman\bomberman_rl\agent_code\dqn_agent3\dqn.py", line 139, in UpdateWeights
    for param in self.Model.parameters():
  File "C:\Users\kinne\anaconda3\lib\site-packages\torch\_tensor.py", line 363, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "C:\Users\kinne\anaconda3\lib\site-packages\torch\autograd\__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
KeyboardInterrupt
